### ISSUE TITLE
TecD Graph Concepts

### ISSUE THREAD

**Issue by monora** [monora/jgraphl#6]
Having the first working version of the graph concepts, we should rethink the interface hierarchy. The concepts of the [Boost Graph Library](http://www.boost.org/doc/libs/1_57_0/libs/graph/doc/graph_concepts.html) should be our guideline. Should we also introduce these interfaces?

* IncidenceGraph and/or AdjacencyGraph
* BidirectionalGraph
* AdjacencyMatrix
* VertexListGraph, EdgeListGraph

**Comment by monora** [comment]
Defined IncidenceGraph, AdjacencyGraph and BidirectionalGraph. Since we always want to have adjacentVertices for a Graph, Graph extends AdjacencyGraph, which defines the protocol to access adjacent vertices. Access to incident edges is not always needed (i.e. in currrent ImplicitGraph implementation). It is therefore in a separat interface not needed for all graphs.

* BidirectionalGraph does not yet have an implementation.
* AdjacencyMatrix can be postponed
* VertexListGraph, EdgeListGraph protocols are for now included as concepts in the Graph protocol

**Comment by monora** [comment]
@trs123 Would you like to review?

**Comment by trs123** [comment]
> @trs123 <https://github.com/trs123> Would you like to review?

of course :-)

**Comment by trs123** [comment]
Did I understand the following correctly?
- AdjacencyGraph is using just vertices but no explicit edges. It is used for use cases where no explicit edges are needed. It provides O(1) access to neighboring vertices. The AdjacencyGraph of the Boost library is directed but I wouldn't require this. Actually I'd use the name ImplicitGraph instead of AdjacencyGraph.
- IncidenceGraph provides O(1) access to explicit edges which are outgoing if directed. Why is it called *Incidence*Graph if the edges are *outgoing*? I've been thinking about suggesting the name ExplicitGraph instead of IncidenceGraph.
- BidirectionalGraph provides O(1) access to explicit incoming *and* outgoing edges.

**Comment by monora** [comment]
trs123 <notifications@github.com> writes:

> Did I understand the following correctly?
Mostly yes :-)
>
> * AdjacencyGraph is using just vertices but no explicit edges. It is used for
>   use cases where no explicit edges are needed. It provides O(1) access to
>   neighboring vertices. The AdjacencyGraph of the Boost library is directed but
>   I wouldn't require this. Actually I'd use the name ImplicitGraph instead of
>   AdjacencyGraph.
BGL does not require AdjacencyGraph to be directed. Where did you read
this? Implicitgraph has a different meaning in RGL. I would like to also
refer to the RGL concepts. Using different names would lead to
misunderstandings.
> * IncidenceGraph provides O(1) access to explicit edges which are outgoing if
>   directed. Why is it called IncidenceGraph if the edges are outgoing? I've been
>   thinking about suggesting the name ExplicitGraph instead of
>   IncidenceGraph.
Hm, same here: Someone knowing the BGL concepts would understand at
once. Did you see that I have copied the documentation from BGL? That's
why I would like to use the same terms as BGL. Therefore we should
rather rename AbstractAdjacencyGraph (and its subclasses) to
AbstractIncidenceGraph because it extends Incidencegraph.
> * BidirectionalGraph provides O(1) access to explicit incoming and outgoing
>   edges.
yes

**Comment by trs123** [comment]
> BGL does not require AdjacencyGraph to be directed. Where did you read this?

Ah, I was mislead by the reference to out_edges() assuming they required to be directed but these may be undirected as well.

**Comment by trs123** [comment]
Review comments:
- I would expect IncidentGraph to introduce explicit edges in form of a type parameter E extends Edge<V>, i.e. IncidentGraph<V, E extends Edge<V>>
- I don't think Graph should be a parent of AdjacencyGraph or IncidenceGraph (BGL has a root concept Graph but that seems to only contain the type definitions), it might rather be a sub interface of both?
